version: "3.9"

services:
  db:
    container_name: warehouse_db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1239
      POSTGRES_DB: warehouse_db
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d warehouse_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  warehouseapplication:
    depends_on:
      db:
        condition: service_healthy
    image: ${DOCKER_REGISTRY-}warehouseapplication
    container_name: warehouse_api
    build:
      context: WarehouseApplication
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=warehouse_db;Username=postgres;Password=1239
    ports:
      - "5000:5000"
      - "5001:5001"
    restart: unless-stopped
