apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-api
  template:
    metadata:
      labels:
        app: warehouse-api
    spec:
      containers:
      - name: warehouse-api
        image: warehouseapplication:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        - containerPort: 5001
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: "http://+:5000;https://+:5001"
        - name: ASPNETCORE_HTTP_PORTS
          value: "5000"
        - name: ASPNETCORE_HTTPS_PORTS
          value: "5001"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=warehouse-db;Port=5432;Database=warehouse_db;Username=postgres;Password=1239"

---
apiVersion: v1
kind: Service
metadata:
  name: warehouse-api
spec:
  selector:
    app: warehouse-api
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  - name: https
    port: 5001
    targetPort: 5001
  type: NodePort
