apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-db
  template:
    metadata:
      labels:
        app: warehouse-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "1239"
        - name: POSTGRES_DB
          value: warehouse_db
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
          name: init-script
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres", "-d", "warehouse_db"]
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 10
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: postgres-init-script

---
apiVersion: v1
kind: Service
metadata:
  name: warehouse-db
spec:
  type: NodePort
  selector:
    app: warehouse-db
  ports:
  - port: 5432
    targetPort: 5432
